databases:
  - name: socialanalytics-db
    databaseName: socialanalytics
    user: socialanalytics
    plan: starter # or free for testing

services:
  - type: web
    name: socialanalytics
    runtime: node
    buildCommand: ./scripts/build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: socialanalytics-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://socialanalytics.onrender.com # Update with your actual domain
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: YOUTUBE_API_KEY
        sync: false # Set manually in Render dashboard
      - key: DISCORD_CLIENT_ID
        sync: false # Set manually in Render dashboard
      - key: DISCORD_CLIENT_SECRET
        sync: false # Set manually in Render dashboard
      - key: DISCORD_GUILD_ID
        sync: false # Set manually in Render dashboard
      - key: DISCORD_COURSE_ROLE_ID
        sync: false # Set manually in Render dashboard
      - key: STRIPE_SECRET_KEY
        sync: false # Set manually in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false # Set manually in Render dashboard
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false # Set manually in Render dashboard
      - key: NEXT_PUBLIC_STRIPE_PRICE_ID
        sync: false # Set manually in Render dashboard
      - key: REDIS_URL
        sync: false # Set manually if using Redis for caching